name: Upload Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install AWS CLI
        run: sudo apt-get install awscli

      - name: List Files in S3
        id: list_s3
        run: |
          aws s3 ls s3://${{ secrets.AWS_S3_BUCKET }}/logs/ > s3_files.txt
          cat s3_files.txt

      - name: Check for Existing Files
        id: check_files
        run: |
          FILES_TO_UPLOAD=()
          for file in logs/*; do
            if ! grep -q $(basename $file) s3_files.txt; then
              FILES_TO_UPLOAD+=($file)
            fi
          done
          echo "FILES_TO_UPLOAD=${FILES_TO_UPLOAD[@]}" >> $GITHUB_ENV

      - name: Upload to S3
        if: env.FILES_TO_UPLOAD != ''
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --follow-symlinks --delete --exclude '.git*/*'
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: 'logs'

      - name: No Files to Upload
        if: env.FILES_TO_UPLOAD == ''
        run: echo "No new files to upload."
