name: Upload Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Upload to S3
        id: s3_sync
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --follow-symlinks --delete --exclude '.git*/*'
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: 'logs'
        continue-on-error: true

      - name: Success Action
        if: success() && steps.s3_sync.conclusion == 'success'
        run: echo "S3 upload succeeded."

      - name: Failure Action
        if: failure() || steps.s3_sync.conclusion == 'failure'
        run: echo "S3 upload failed. Taking alternative action."
